'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function PartnerSignIn() {
  const [method, setMethod] = useState<'password' | 'code'>('password');
  const [codeSent, setCodeSent] = useState(false);
  const [message, setMessage] = useState('');
  const router = useRouter();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); sessionStorage.setItem('cadence-demo-partner', 'signed-in'); router.push('/partner/dashboard'); };
  return <div className="portal"><nav className="nav"><Link className="brand" href="/">Cadence</Link><span style={{ fontSize: 14 }}>Partner portal</span><Link style={{ marginLeft: 'auto' }} href="/">cadence.com</Link></nav><main className="portal-main"><div className="card"><span className="tag">Encrypted sign-in · demo</span><h1 style={{ marginBottom: 6 }}>Sign in</h1><p className="body-copy" style={{ fontSize: 13.5 }}>For Friends & Coaches only — this does not authenticate a real account.</p><div className="seg" style={{ marginBlock: 20 }}><label><input type="radio" checked={method === 'password'} onChange={() => { setMethod('password'); setCodeSent(false); }} /> Password</label><label><input type="radio" checked={method === 'code'} onChange={() => { setMethod('code'); setCodeSent(false); }} /> Email code</label></div><form onSubmit={submit} className="contact-form"><div className="field"><label htmlFor="work-email">Work email</label><input id="work-email" className="input" type="email" placeholder="you@cadence.coach" required /></div>{method === 'password' ? <><div className="field"><label htmlFor="password">Password</label><input id="password" className="input" type="password" required /></div><div className="row" style={{ justifyContent: 'space-between' }}><label style={{ fontSize: 13 }}><input type="checkbox" /> Keep me signed in</label><a href="#" onClick={(event) => { event.preventDefault(); setMessage('Password recovery is unavailable in this demo.'); }}>Forgot password?</a></div><button className="button">Sign in to demo</button></> : <>{!codeSent ? <button type="button" className="button secondary" onClick={() => { setCodeSent(true); setMessage('Demo code sent — no email was delivered.'); }}>Send sign-in code</button> : <><p className="notice" role="status">Demo code sent — no email was delivered. Enter any six digits to continue.</p><div className="field"><label htmlFor="code">6-digit code</label><input id="code" className="input" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required /></div><button className="button">Verify & sign in</button></>}</>}</form>{message && <p className="notice" role="status" style={{ marginTop: 16 }}>{message}</p>}<hr className="rule" style={{ margin: '24px 0' }} /><p className="body-copy" style={{ fontSize: 12 }}>Independent contractor access only. This screen is illustrative and does not create a credential, session record, or agreement.</p><p style={{ fontSize: 13, marginBottom: 0 }}>New here? <a href="#">Apply to become a Friend or Coach</a></p></div></main><footer className="footer" style={{ textAlign: 'center' }}>Prefer the app? <a href="#">Download for iOS</a> · <a href="#">Android</a></footer></div>;
}
